/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";*/
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import Header from "@/components/Headers/Header";
import Footer from "@/components/Footer/Footer";
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/


// @ts-ignore
export default function RootLayout({children}) {
  // @ts-ignore
  return (
    <html lang="en">
      <body >
        <div className="container py-3">
            <Header />
            <main>{children}</main>
            <Footer />
        </div>
      </body>
    </html>
  );
}
